# Form implementation generated from reading ui file 'aNewAltmanAug9.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(508, 163)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #121212;\n"
"color:#fff;\n"
"font:9pt \"Helvetica\";\n"
"}\n"
"\n"
"QLabel {\n"
"background:transparent;\n"
"font-size:10pt;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"                                 QSlider\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: rgba(22,22,22,100);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(32, 32, 32);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(255, 88, 71);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: white;\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color:white;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QSlider\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider:vertical {\n"
"min-width:40px;\n"
"min-height:90px;\n"
"max-height:90px;\n"
"}\n"
"QSlider::groove:vertical {\n"
"border-radius: 7px;\n"
"width: 40px;\n"
"margin: 0px;\n"
"background:rgb(22, 24, 29);\n"
"}\n"
"\n"
"QSlider::groove:vertical:hover {\n"
"background: rgba(233,123,111,0.25);\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"background: rgb(233,123,111);\n"
"height: 18px;\n"
"width: 40px;\n"
"margin: 0px;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"background:transparent;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"background-color: rgb(255,163,151);\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"background-color:rgb(188,78,66);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////////////////////////////\n"
"                                    QScrollBar\n"
"//////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background:transparent;\n"
"    height: 12px;\n"
"    margin: 0px 10px 0px 10px;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(22,22,22);\n"
"    min-width:24px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, \n"
"QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, \n"
"QScrollBar::sub-page:horizontal {\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color:transparent;\n"
"    width: 12px;\n"
"    margin: 10px 0px 10px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(22,22,22);\n"
"    min-height: 12px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical, \n"
"QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, \n"
"QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_12.setContentsMargins(4, 9, 4, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.mainStack = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.mainStack.setStyleSheet("QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"background-color: transparent;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.mainStack.setObjectName("mainStack")
        self.altmansQuestionPage = QtWidgets.QWidget()
        self.altmansQuestionPage.setObjectName("altmansQuestionPage")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.altmansQuestionPage)
        self.gridLayout_24.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_24.setSpacing(0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.altmanQuestionStack = QtWidgets.QStackedWidget(parent=self.altmansQuestionPage)
        self.altmanQuestionStack.setStyleSheet("QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"margin-left:9px;\n"
"padding-top:2px;\n"
"padding-bottom:2px;\n"
"background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: transparent;\n"
"font-weight:bold;\n"
"font-size:8pt;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    border-radius: 4px;\n"
"    \n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.altmanQuestionStack.setObjectName("altmanQuestionStack")
        self.question = QtWidgets.QWidget()
        self.question.setObjectName("question")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.question)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(parent=self.question)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.altman_question = QtWidgets.QSlider(parent=self.frame)
        self.altman_question.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(87,111,215);}\n"
"QSlider::handle:vertical:hover {background:rgb(127,151,255);}\n"
"QSlider::handle:vertical:pressed {background:rgb(37,61,165);}\n"
"QSlider::groove:vertical:hover {background:rgba(87,111,215,0.25);}\n"
"QSlider::groove:vertical {background:rgba(87,111,215,0.15);}\n"
"\n"
"        ")
        self.altman_question.setMaximum(4)
        self.altman_question.setTracking(True)
        self.altman_question.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altman_question.setInvertedAppearance(True)
        self.altman_question.setObjectName("altman_question")
        self.horizontalLayout_2.addWidget(self.altman_question)
        self.frame1 = QtWidgets.QFrame(parent=self.frame)
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setContentsMargins(12, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.frame1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.frame1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.frame1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(parent=self.frame1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=self.frame1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_2.addWidget(self.frame1)
        self.verticalLayout_2.addWidget(self.frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.altmanQuestionStack.addWidget(self.question)
        self.question1 = QtWidgets.QWidget()
        self.question1.setObjectName("question1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.question1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.frame2 = QtWidgets.QFrame(parent=self.question1)
        self.frame2.setObjectName("frame2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.altman_question_2 = QtWidgets.QSlider(parent=self.frame2)
        self.altman_question_2.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(68,212,146);}\n"
"QSlider::handle:vertical:hover {background:rgb(108,252,186);}\n"
"QSlider::handle:vertical:pressed {background:rgb(18,162,96);}\n"
"QSlider::groove:vertical:hover {background:rgba(68,212,146,0.25);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(68,212,146,0.15);}\n"
"\n"
"        ")
        self.altman_question_2.setMaximum(4)
        self.altman_question_2.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altman_question_2.setInvertedAppearance(True)
        self.altman_question_2.setObjectName("altman_question_2")
        self.horizontalLayout_3.addWidget(self.altman_question_2)
        self.frame3 = QtWidgets.QFrame(parent=self.frame2)
        self.frame3.setObjectName("frame3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame3)
        self.verticalLayout_3.setContentsMargins(12, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(parent=self.frame3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.frame3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_11 = QtWidgets.QLabel(parent=self.frame3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(parent=self.frame3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(parent=self.frame3)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.horizontalLayout_3.addWidget(self.frame3)
        self.verticalLayout_4.addWidget(self.frame2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.altmanQuestionStack.addWidget(self.question1)
        self.question2 = QtWidgets.QWidget()
        self.question2.setObjectName("question2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.question2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.frame4 = QtWidgets.QFrame(parent=self.question2)
        self.frame4.setObjectName("frame4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.altman_question_3 = QtWidgets.QSlider(parent=self.frame4)
        self.altman_question_3.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(245,235,103);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,255,143);}\n"
"QSlider::handle:vertical:pressed {background:rgb(195,185,53);}\n"
"QSlider::groove:vertical:hover {background:rgba(245,235,103,0.25);}\n"
"QSlider::groove:vertical {background:rgba(245,235,103,0.15);}\n"
"        ")
        self.altman_question_3.setMaximum(4)
        self.altman_question_3.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altman_question_3.setInvertedAppearance(True)
        self.altman_question_3.setObjectName("altman_question_3")
        self.horizontalLayout_4.addWidget(self.altman_question_3)
        self.frame5 = QtWidgets.QFrame(parent=self.frame4)
        self.frame5.setObjectName("frame5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame5)
        self.verticalLayout_5.setContentsMargins(12, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_10 = QtWidgets.QLabel(parent=self.frame5)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.label_14 = QtWidgets.QLabel(parent=self.frame5)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(parent=self.frame5)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.label_17 = QtWidgets.QLabel(parent=self.frame5)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_5.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(parent=self.frame5)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_5.addWidget(self.label_18)
        self.horizontalLayout_4.addWidget(self.frame5)
        self.verticalLayout_6.addWidget(self.frame4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.altmanQuestionStack.addWidget(self.question2)
        self.question3 = QtWidgets.QWidget()
        self.question3.setObjectName("question3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.question3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.frame6 = QtWidgets.QFrame(parent=self.question3)
        self.frame6.setObjectName("frame6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.altman_question_4 = QtWidgets.QSlider(parent=self.frame6)
        self.altman_question_4.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(255,161,92);}\n"
"QSlider::handle:vertical:hover {background:rgb(255,201,132);}\n"
"QSlider::handle:vertical:pressed {background:rgb(205,111,42);}\n"
"QSlider::groove:vertical:hover {background:rgba(255,161,92,0.25);}\n"
"QSlider::groove:vertical {background:rgba(255,161,92,0.15);}\n"
"\n"
"        ")
        self.altman_question_4.setMaximum(4)
        self.altman_question_4.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altman_question_4.setInvertedAppearance(True)
        self.altman_question_4.setObjectName("altman_question_4")
        self.horizontalLayout_5.addWidget(self.altman_question_4)
        self.frame7 = QtWidgets.QFrame(parent=self.frame6)
        self.frame7.setObjectName("frame7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame7)
        self.verticalLayout_7.setContentsMargins(12, -1, -1, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_16 = QtWidgets.QLabel(parent=self.frame7)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.label_19 = QtWidgets.QLabel(parent=self.frame7)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_7.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(parent=self.frame7)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_7.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(parent=self.frame7)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        self.label_24 = QtWidgets.QLabel(parent=self.frame7)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_7.addWidget(self.label_24)
        self.horizontalLayout_5.addWidget(self.frame7)
        self.verticalLayout_8.addWidget(self.frame6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.altmanQuestionStack.addWidget(self.question3)
        self.question4 = QtWidgets.QWidget()
        self.question4.setObjectName("question4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.question4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem8)
        self.frame8 = QtWidgets.QFrame(parent=self.question4)
        self.frame8.setObjectName("frame8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.altman_question_5 = QtWidgets.QSlider(parent=self.frame8)
        self.altman_question_5.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(199,76,81);}\n"
"QSlider::handle:vertical:hover {background:rgb(239,116,121);}\n"
"QSlider::handle:vertical:pressed {background:rgb(149,26,31);}\n"
"QSlider::groove:vertical:hover {background:rgba(199,76,81,0.25);}\n"
"QSlider::groove:vertical {background:rgba(199,76,81,0.15);}\n"
"\n"
"        ")
        self.altman_question_5.setMaximum(4)
        self.altman_question_5.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altman_question_5.setInvertedAppearance(True)
        self.altman_question_5.setObjectName("altman_question_5")
        self.horizontalLayout_6.addWidget(self.altman_question_5)
        self.frame9 = QtWidgets.QFrame(parent=self.frame8)
        self.frame9.setObjectName("frame9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame9)
        self.verticalLayout_9.setContentsMargins(12, -1, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_28 = QtWidgets.QLabel(parent=self.frame9)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_9.addWidget(self.label_28)
        self.label_22 = QtWidgets.QLabel(parent=self.frame9)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_9.addWidget(self.label_22)
        self.label_25 = QtWidgets.QLabel(parent=self.frame9)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_9.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(parent=self.frame9)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_9.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(parent=self.frame9)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_9.addWidget(self.label_27)
        self.horizontalLayout_6.addWidget(self.frame9)
        self.verticalLayout_10.addWidget(self.frame8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem9)
        self.altmanQuestionStack.addWidget(self.question4)
        self.altmanScore = QtWidgets.QWidget()
        self.altmanScore.setObjectName("altmanScore")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.altmanScore)
        self.gridLayout_9.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame10 = QtWidgets.QFrame(parent=self.altmanScore)
        self.frame10.setObjectName("frame10")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame10)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame11 = QtWidgets.QFrame(parent=self.frame10)
        self.frame11.setObjectName("frame11")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame11)
        self.gridLayout_3.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_3.setHorizontalSpacing(12)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame11)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 306))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_8.addItem(spacerItem10, 7, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 5, 0, 1, 2)
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 2)
        self.altmans_summary_label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.altmans_summary_label.setStyleSheet("font-weight:bold;margin-top:4px; margin-bottom:4px;font-size:14pt;")
        self.altmans_summary_label.setObjectName("altmans_summary_label")
        self.gridLayout_8.addWidget(self.altmans_summary_label, 1, 0, 1, 2, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.altmans_summary = QtWidgets.QSlider(parent=self.frame11)
        self.altmans_summary.setStyleSheet("\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(244,56,81);}\n"
"QSlider::handle:vertical:hover {background:rgb(239,116,121);}\n"
"QSlider::handle:vertical:pressed {background:rgb(149,26,31);}\n"
"QSlider::groove:vertical:hover {background:rgba(199,76,81,0.25);}\n"
"QSlider::groove:vertical {background:rgba(199,76,81,0.35);}\n"
"\n"
"        ")
        self.altmans_summary.setMaximum(20)
        self.altmans_summary.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.altmans_summary.setInvertedAppearance(True)
        self.altmans_summary.setObjectName("altmans_summary")
        self.gridLayout_3.addWidget(self.altmans_summary, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame11, 2, 1, 1, 2)
        self.gridLayout_9.addWidget(self.frame10, 1, 1, 1, 1)
        self.altmanQuestionStack.addWidget(self.altmanScore)
        self.gridLayout_24.addWidget(self.altmanQuestionStack, 0, 0, 1, 1)
        self.mainStack.addWidget(self.altmansQuestionPage)
        self.altmansTablePage = QtWidgets.QWidget()
        self.altmansTablePage.setObjectName("altmansTablePage")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.altmansTablePage)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.altmans_table = QtWidgets.QTableView(parent=self.altmansTablePage)
        self.altmans_table.setStyleSheet("\n"
"QTableView {\n"
"background-color: transparent;\n"
"selection-background-color: #7e57c2;\n"
"gridline-color:transparent;\n"
"color: rgb(77, 15, 26);\n"
"}\n"
"QTableView::item {\n"
"padding: 1px;color: rgb(77, 15, 26);\n"
"background:rgb(229,100,111);\n"
"}\n"
"QTableView::item:selected {\n"
"    color: rgb(255, 255, 255);\n"
"background:rgb(23, 23, 23);\n"
"}\n"
"    ")
        self.altmans_table.setShowGrid(False)
        self.altmans_table.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.altmans_table.setSortingEnabled(True)
        self.altmans_table.setObjectName("altmans_table")
        self.altmans_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_25.addWidget(self.altmans_table, 0, 0, 1, 1)
        self.mainStack.addWidget(self.altmansTablePage)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.hidemeframe = QtWidgets.QFrame(parent=self.page)
        self.hidemeframe.setObjectName("hidemeframe")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.hidemeframe)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.altman_time = QtWidgets.QTimeEdit(parent=self.hidemeframe)
        self.altman_time.setObjectName("altman_time")
        self.horizontalLayout.addWidget(self.altman_time)
        self.altman_date = QtWidgets.QDateEdit(parent=self.hidemeframe)
        self.altman_date.setObjectName("altman_date")
        self.horizontalLayout.addWidget(self.altman_date)
        self.gridLayout_10.addWidget(self.hidemeframe, 0, 0, 1, 1)
        self.mainStack.addWidget(self.page)
        self.gridLayout_12.addWidget(self.mainStack, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 508, 14))
        self.menubar.setObjectName("menubar")
        self.menuBECK = QtWidgets.QMenu(parent=self.menubar)
        self.menuBECK.setObjectName("menuBECK")
        self.menuViews = QtWidgets.QMenu(parent=self.menubar)
        self.menuViews.setObjectName("menuViews")
        MainWindow.setMenuBar(self.menubar)
        self.actionCommit = QtGui.QAction(parent=MainWindow)
        self.actionCommit.setObjectName("actionCommit")
        self.actionDelete = QtGui.QAction(parent=MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionShowAltmanExam = QtGui.QAction(parent=MainWindow)
        self.actionShowAltmanExam.setObjectName("actionShowAltmanExam")
        self.actionShowAltmanTable = QtGui.QAction(parent=MainWindow)
        self.actionShowAltmanTable.setObjectName("actionShowAltmanTable")
        self.actionNext = QtGui.QAction(parent=MainWindow)
        self.actionNext.setObjectName("actionNext")
        self.actionPrev = QtGui.QAction(parent=MainWindow)
        self.actionPrev.setObjectName("actionPrev")
        self.actionHome = QtGui.QAction(parent=MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionMeasureView = QtGui.QAction(parent=MainWindow)
        self.actionMeasureView.setObjectName("actionMeasureView")
        self.menuBECK.addAction(self.actionCommit)
        self.menuBECK.addAction(self.actionDelete)
        self.menuViews.addAction(self.actionShowAltmanExam)
        self.menuViews.addAction(self.actionShowAltmanTable)
        self.menuViews.addAction(self.actionNext)
        self.menuViews.addAction(self.actionPrev)
        self.menuViews.addAction(self.actionHome)
        self.menuViews.addAction(self.actionMeasureView)
        self.menubar.addAction(self.menuBECK.menuAction())
        self.menubar.addAction(self.menuViews.menuAction())

        self.retranslateUi(MainWindow)
        self.mainStack.setCurrentIndex(0)
        self.altmanQuestionStack.setCurrentIndex(4)
        self.altmans_summary.valueChanged['int'].connect(self.altmans_summary_label.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "I do not feel happier or more cheerful than usual."))
        self.label_4.setText(_translate("MainWindow", "I occasionally feel happier or more cheerful than usual."))
        self.label_5.setText(_translate("MainWindow", "I often feel happier or more cheerful than usual."))
        self.label_6.setText(_translate("MainWindow", "I feel happier or more cheerful than usual most of the time."))
        self.label_7.setText(_translate("MainWindow", "I feel happier or more cheerful than usual all of the time."))
        self.label_8.setText(_translate("MainWindow", "I do not feel more self-confident than usual."))
        self.label_9.setText(_translate("MainWindow", "I occasionally feel more self-confident than usual."))
        self.label_11.setText(_translate("MainWindow", "I often feel more self-confident than usual."))
        self.label_12.setText(_translate("MainWindow", "I feel more self-confident than usual."))
        self.label_13.setText(_translate("MainWindow", "I feel extremely self-confident all of the time."))
        self.label_10.setText(_translate("MainWindow", "I do not need less sleep than usual."))
        self.label_14.setText(_translate("MainWindow", "I occasionally need less sleep than usual."))
        self.label_15.setText(_translate("MainWindow", "I often need less sleep than usual."))
        self.label_17.setText(_translate("MainWindow", "I frequently need less sleep than usual."))
        self.label_18.setText(_translate("MainWindow", "I can go all day and night without any sleep and still not feel tired."))
        self.label_16.setText(_translate("MainWindow", "I do not talk more than usual."))
        self.label_19.setText(_translate("MainWindow", "I occasionally talk more than usual."))
        self.label_20.setText(_translate("MainWindow", "I often talk more than usual."))
        self.label_21.setText(_translate("MainWindow", "I frequently talk more than usual."))
        self.label_24.setText(_translate("MainWindow", "I talk constantly and cannot be interrupted."))
        self.label_28.setText(_translate("MainWindow", "I have not been more active than usual."))
        self.label_22.setText(_translate("MainWindow", "I have occasionally been more active than usual."))
        self.label_25.setText(_translate("MainWindow", "I have often been more active than usual."))
        self.label_26.setText(_translate("MainWindow", "I have frequently been more active than usual."))
        self.label_27.setText(_translate("MainWindow", "I am constantly active or on the go all the time."))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">• A cutoff score of 6 </span>or higher indicates a high probability of a manic or hypomanic condition (based on a sensitivity rating of 85.5% and a specificity rating of 87.3%).</p><p><span style=\" font-weight:600;\">• A score of 6 </span>or higher may indicate a need for treatment and/or further diagnostic workup to confirm a diagnosis of mania or hypomania.</p><p><span style=\" font-weight:600;\">• A score of 5</span> or lower is less likely to be associated with significant symptoms of mania.</p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">How Manic Are You?</span></p></body></html>"))
        self.altmans_summary_label.setText(_translate("MainWindow", "0"))
        self.altman_time.setDisplayFormat(_translate("MainWindow", "hh:mm:ss"))
        self.altman_date.setDisplayFormat(_translate("MainWindow", "yyyy/mm/dd"))
        self.menuBECK.setTitle(_translate("MainWindow", "Altman"))
        self.menuViews.setTitle(_translate("MainWindow", "Views"))
        self.actionCommit.setText(_translate("MainWindow", "Commit"))
        self.actionCommit.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionDelete.setText(_translate("MainWindow", "Delete Record"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.actionShowAltmanExam.setText(_translate("MainWindow", "Input View"))
        self.actionShowAltmanExam.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionShowAltmanTable.setText(_translate("MainWindow", "Dataview"))
        self.actionShowAltmanTable.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.actionNext.setText(_translate("MainWindow", "Next Question"))
        self.actionNext.setShortcut(_translate("MainWindow", "Alt+2"))
        self.actionPrev.setText(_translate("MainWindow", "Previous Question"))
        self.actionPrev.setShortcut(_translate("MainWindow", "Alt+1"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionHome.setShortcut(_translate("MainWindow", "Alt+3"))
        self.actionMeasureView.setText(_translate("MainWindow", "Measure View"))
        self.actionMeasureView.setShortcut(_translate("MainWindow", "Alt+4"))
